# Generated by Django 3.2 on 2021-06-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('passwd', models.CharField(max_length=128)),
                ('salt', models.CharField(max_length=8)),
                ('reg_time', models.DateTimeField()),
            ],
        ),
    ]
