# Generated by Django 3.2 on 2021-06-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
